apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  jwt-secret:    {{ .Values.secret.jwtSecret | quote }}
  mongo-user:    {{ .Values.secret.mongoUser | quote }}
  mongo-password: {{ .Values.secret.mongoPassword | quote }}
  mongo-auth-db: {{ .Values.secret.mongoAuthDb | quote }}
